### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by ekudel**
Support websockets through HTTP proxy

### CODE REVIEW

**Comment by nkzawa** [comment]
Thanks for your PR! but can you explain the details ?

**Comment by ekudel** [comment]
Sorry about the delay. It's possibility to establish connection through proxy. proxyHost, proxyPort proxyLogin, proxyPassword are parameters to pass to okhttp websocket client. As about HttpConnectionProvider, it is used in PollingXHR. Using this, anyone can customize HTTP connection, usually pass some proxy to URL.openConnection(Proxy) method. Yes, it works only for POLLING, but client code can use proxy Java API classes, such as Proxy, ProxySelector, etc

**Comment by ekudel** [comment]
Any updates? I can perform some changes in the code, if it is necessary.

**Comment by nkzawa** [comment]
Sorry for the delay. We have to set up Proxy in different ways for HTTP and Websocket ? I think it should be transparent as much as possible.

**Comment by ekudel** [comment]
Ok, I've simplified the API

**Comment by ekudel** [comment]
Any updates?

**Comment by nkzawa** [comment]
@ekudel sorry for the delay, it looks amazing! Thank you!!

**Comment by nkzawa** [comment]
Maybe it's nice to set `Proxy-Authorization` header for polling requests too?

**Pull request merged**
