### PR TITLE
upgrade okhttp to 2.5.0

### PR DESCRIPTION
**Pull request by b95505017**

### CODE REVIEW

**Comment by nkzawa** [comment]
thank you always !

**Comment by b95505017** [comment]
:+1:

**Comment by b95505017** [comment]
According to this commit:
https://github.com/square/okhttp/commit/0de14e992c228fd9de9fe78417788131bee00902
OkHttp 2.5.0 now add default timeout 10s, maybe we should be able to set it in option?

**Comment by nkzawa** [comment]
I think these default values are appropriate for most cases. We can add the options later if it's really required.

**Pull request merged**
