### PR TITLE
fix https://github.com/square/okhttp/issues/2283 SecurityException

### PR DESCRIPTION
**Pull request by xuduo**
fix SecurityException crash on some android devices in some circumstances.

### CODE REVIEW

**Comment by nkzawa** [comment]
Sorry for the delay, but I wonder if there is a way to reproduce the problem.

**Comment by xuduo** [comment]
Maybe if you don't add internet permission on androidManifest, have not tried.
In my case, I have this permission on androidManifest,  It's from app crash report.

**Comment by xuduo** [comment]
I successfully fixed this crash by using this commit

**Comment by nkzawa** [comment]
🤔  but basically, you'd need internet permission to use this lib, right ?

Anyway, it seems this problem would be addressable with `websocketFactory` option which you can set the dns settings as well.

https://github.com/socketio/engine.io-client-java/pull/85

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Pull request closed without merging**
